# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ubt_msgs/face_attribute.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class face_attribute(genpy.Message):
  _md5sum = "29a30379f8f2433a696aa714536f8c8b"
  _type = "ubt_msgs/face_attribute"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 age
int32 gender
int32 smile # score 0-100
int32 faceQuality
int32 faceScore
int32 faceGlass
int32 faceMask
int32 expression"""
  __slots__ = ['age','gender','smile','faceQuality','faceScore','faceGlass','faceMask','expression']
  _slot_types = ['int32','int32','int32','int32','int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       age,gender,smile,faceQuality,faceScore,faceGlass,faceMask,expression

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(face_attribute, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.age is None:
        self.age = 0
      if self.gender is None:
        self.gender = 0
      if self.smile is None:
        self.smile = 0
      if self.faceQuality is None:
        self.faceQuality = 0
      if self.faceScore is None:
        self.faceScore = 0
      if self.faceGlass is None:
        self.faceGlass = 0
      if self.faceMask is None:
        self.faceMask = 0
      if self.expression is None:
        self.expression = 0
    else:
      self.age = 0
      self.gender = 0
      self.smile = 0
      self.faceQuality = 0
      self.faceScore = 0
      self.faceGlass = 0
      self.faceMask = 0
      self.expression = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_8i().pack(_x.age, _x.gender, _x.smile, _x.faceQuality, _x.faceScore, _x.faceGlass, _x.faceMask, _x.expression))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.age, _x.gender, _x.smile, _x.faceQuality, _x.faceScore, _x.faceGlass, _x.faceMask, _x.expression,) = _get_struct_8i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_8i().pack(_x.age, _x.gender, _x.smile, _x.faceQuality, _x.faceScore, _x.faceGlass, _x.faceMask, _x.expression))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.age, _x.gender, _x.smile, _x.faceQuality, _x.faceScore, _x.faceGlass, _x.faceMask, _x.expression,) = _get_struct_8i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8i = None
def _get_struct_8i():
    global _struct_8i
    if _struct_8i is None:
        _struct_8i = struct.Struct("<8i")
    return _struct_8i
