from ._action import *
from ._analyze_april_tag_single_image import *
from ._battery_read import *
from ._board_read import *
from ._check_april_tag_status import *
from ._check_qr_status import *
from ._combine_request import *
from ._ctrl_april_tag_continuous_detector import *
from ._ctrl_camera_enable import *
from ._ctrl_http_image_server import *
from ._ctrl_qr_detector import *
from ._custom_motion_list_get import *
from ._data_base_request import *
from ._device_addr import *
from ._enable_get import *
from ._enable_set import *
from ._energy_saving_task_status_set import *
from ._env_read import *
from ._ext_read import *
from ._gait_status import *
from ._gait_status_read import *
from ._gamepad_conf_content_get import *
from ._gamepad_conf_content_set import *
from ._gamepad_conf_file_set import *
from ._gamepad_conf_name_get import *
from ._gyro_read import *
from ._hts_status_change import *
from ._i2c_upgrade import *
from ._led import *
from ._led_reply import *
from ._motion_planning import *
from ._motion_planning_status import *
from ._move_status import *
from ._music_play import *
from ._music_status import *
from ._object_tracking_config import *
from ._object_tracking_task import *
from ._play_motion_hts import *
from ._robot_status_set import *
from ._sensor_calibrate_set import *
from ._sensor_report_enable import *
from ._servo_active import *
from ._servo_clear import *
from ._servo_layer import *
from ._servo_offset_read import *
from ._servo_offset_write import *
from ._servo_read import *
from ._servo_write import *
from ._string_set import *
from ._task_configuration_get import *
from ._task_configuration_set import *
from ._ubt_interrupt_action import *
from ._value_get import *
from ._value_set import *
from ._version_read import *
from ._vision_ai_event import *
from ._vision_camera_request import *
from ._vision_detect import *
from ._vision_face_attr_result import *
from ._vision_get import *
from ._vision_monitor import *
from ._vision_recognition import *
from ._vision_remote_set import *
from ._vision_report_color import *
from ._vision_report_expression import *
from ._vision_report_face_attr import *
from ._vision_report_gesture import *
from ._vision_report_int import *
from ._vision_report_str import *
from ._vision_set import *
from ._vision_status import *
from ._vision_stream import *
from ._vision_take_photo import *
from ._vision_task_set import *
from ._voice_asr_iat_result import *
from ._voice_asr_offlinesyntax_get import *
from ._voice_asr_offlinesyntax_grammar_get import *
from ._voice_asr_offlinesyntax_set import *
from ._voice_asr_start import *
from ._voice_asr_stop import *
from ._voice_asr_subscribe import *
from ._voice_iat_detectedmsg import *
from ._voice_iat_start import *
from ._voice_iat_stop import *
from ._voice_tts_by_id_start import *
from ._voice_tts_start import *
from ._voice_tts_status import *
from ._voice_tts_stop import *
from ._volume_get import *
from ._volume_set import *
